# Maven group ID used for all components
componentsGroupId: "com.foamball.volte.android"

# Synchronized build configuration for all modules
compileSdkVersion: 34
minSdkVersion: 21
targetSdkVersion: 33
